# Generated by Django 2.2.5 on 2020-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='present',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='student',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
